# Generated by Django 5.2.6 on 2025-09-28 05:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flocks', '0003_mortalitycause_mortalityrecord'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncConflict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(max_length=50)),
                ('client_id', models.CharField(blank=True, max_length=100, null=True)),
                ('payload', models.JSONField()),
                ('resolution', models.CharField(blank=True, max_length=50, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('flock', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='flocks.flock')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['source', 'client_id'], name='flocks_sync_source_1558b7_idx'), models.Index(fields=['resolved_at'], name='flocks_sync_resolve_6635fb_idx')],
            },
        ),
    ]
